### ISSUE TITLE
Can't load unknown script

### ISSUE THREAD

**Issue by Metoku** [StratusFearMe21/mpv-presence#1]
Hi I tried putting it in the scripts folder and the console outputs this. I most likely did the installation wrong idk
![ss](https://user-images.githubusercontent.com/59681368/140594287-af1311a1-b6d8-4f50-a136-5d2b1ef67577.jpg)

**Comment by StratusFearMe21** [comment]
Thanks for taking interest in my plugin! You are using Windows so the `libmpv_presence.so` file will not work. I've just added a Windows build to the latest release, try swapping out the `libmpv_presence.so` file with the `mpv_presence.dll` file in the latest release!

**Comment by Metoku** [comment]
I see thanks for responding. I'm still having the same error when I replaced it with the new file from the latest release.

**Comment by StratusFearMe21** [comment]
Yeah, this project was made for Linux, not windows, but theoretically this plugin should be cross-platform, I'll let you know when I've figured out how to build for Windows

**Comment by Metoku** [comment]
Sure thing take your time bro. I open github everyday anyways thanks for the hard work.

**Comment by StratusFearMe21** [comment]
Do you know if your MPV is compiled with C Plugin support? If your copy of MPV is from [here](https://sourceforge.net/projects/mpv-player-windows/), or from `scoop`, then MPV is not compiled with C Plugin support, I will get back to you when I figure out how to get a working build to you.

**Comment by StratusFearMe21** [comment]
Well, shit, all that work building MPV with C Plugins, and found this in the MPV docs, sorry mate
![bruh](https://user-images.githubusercontent.com/57533634/141015922-ed88ed5d-f09f-4dec-92c9-be31efdfcf02.png)

**Comment by StratusFearMe21** [comment]
In other words, this plugin is exclusively for Linux and BSD users. (Didn't know about this limitation until now)

**Comment by Metoku** [comment]
Oh too bad its not available for my system. Thanks for explaining why though.
