### ISSUE TITLE
[OOT]

### ISSUE THREAD

**Issue by lidgnulinux** [StratusFearMe21/mpv-presence#2]
Hi sorry to fill unrelated issue, I found your comment on dwl's issue page and you said that you've implemented vanity gaps and more. May I know about it ? I was trying gaps patch from PATCH page but no luck (it's outdated). Thanks. Feel free to remove this .

**Comment by StratusFearMe21** [comment]
That's weird, I'm also using the vanity gaps patch from the wiki

**Comment by StratusFearMe21** [comment]
btw, if a patch doesn't apply properly, it's usually very easy to open the patch file and apply it manually
