### ISSUE TITLE
Time left count keep going even when mpv is paused

### ISSUE THREAD

**Issue by datsfilipe** [StratusFearMe21/mpv-presence#4]
What happens:

![test](https://user-images.githubusercontent.com/76636791/185754237-5f55e609-b60b-4eb0-9405-0f84d8dd34c5.gif)

This happens till the time reach in 0, then it stops and if I press play again, It get back to normal, showing the time left count correctly.

**Comment by StratusFearMe21** [comment]
Unfortunately, this is a flaw of Discord's rich presence API. It's not possible for me to pause the time left indicator (sorry about that).
